### PR TITLE
support kinetic

### PR DESCRIPTION
**Pull request by ompugao**
please do not merge yet

### CODE REVIEW

**Comment by ShotaAk** [comment]
@ompugao  Thanks. 

Currently, we don't have a PC installed Ubuntu 16.04 & ROS Kinetic.
So, we can't test your pull request immediately... 
We prepare the PC, ASAP.  Thank you!

**Comment by ompugao** [comment]
@ShotaAk Thanks! it will take time to complete this pr, so you do not need to rush to prepare your pc ;)

**Comment by ompugao** [comment]
could you create a new branch named like "kinetic-devel" and merge this pr into it if you don't mind?
if you do that, other people can also carry on implementing this feature.

**Comment by ShotaAk** [comment]
Ok! I created it.

**Comment by ompugao** [comment]
thanks! I changed the base branch

**Comment by ompugao** [comment]
could you merge this
?

**Comment by ShotaAk** [comment]
I already merged this PR into kinetic-devel branch. 👍

**Comment by ompugao** [comment]
oh, nice! thanks!

**Pull request closed without merging**
